// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbDqKwtLy2YQClJP8ZBoUXh_Vc41jFgM',
    appId: '1:807249892823:web:98a2f7e8746cd7d3aa2792',
    messagingSenderId: '807249892823',
    projectId: 'footnet-530f3',
    authDomain: 'footnet-530f3.firebaseapp.com',
    storageBucket: 'footnet-530f3.appspot.com',
    measurementId: 'G-C2X5H6STT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxPxMljSqPYFxdvB3ZCb4uROcZL00kX4',
    appId: '1:807249892823:android:cfb5813f1739afd5aa2792',
    messagingSenderId: '807249892823',
    projectId: 'footnet-530f3',
    storageBucket: 'footnet-530f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdOTpdkUHuiy-zsNW5EC02DaSAbBuYj3Y',
    appId: '1:807249892823:ios:66c35cddd81cc5eaaa2792',
    messagingSenderId: '807249892823',
    projectId: 'footnet-530f3',
    storageBucket: 'footnet-530f3.appspot.com',
    iosClientId: '807249892823-ku5m6esbesn7is4n8bv95t9bo6dee6ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.footnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdOTpdkUHuiy-zsNW5EC02DaSAbBuYj3Y',
    appId: '1:807249892823:ios:66c35cddd81cc5eaaa2792',
    messagingSenderId: '807249892823',
    projectId: 'footnet-530f3',
    storageBucket: 'footnet-530f3.appspot.com',
    iosClientId: '807249892823-ku5m6esbesn7is4n8bv95t9bo6dee6ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.footnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJbDqKwtLy2YQClJP8ZBoUXh_Vc41jFgM',
    appId: '1:807249892823:web:4db1b4f720586f85aa2792',
    messagingSenderId: '807249892823',
    projectId: 'footnet-530f3',
    authDomain: 'footnet-530f3.firebaseapp.com',
    storageBucket: 'footnet-530f3.appspot.com',
    measurementId: 'G-FMKB156B16',
  );

}